name: CI

on: [push, pull_request]

jobs:
  
  build_ps4:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Build Files
        run: |
          ./_build.bat
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB4DX-PS4
          path: _build